### ISSUE TITLE
Setup artcompiler.com domains to point to {app, api}

### ISSUE THREAD

**Issue by KevinDyer** [graffiticode/graffiticode#24]

**Comment by KevinDyer** [comment]
The table below are my thoughts on the domains we should setup @jeffdyer wdyt?

project | staging | prod
--- | --- | ---
app | staging.app.artcompiler.com | app.artcompiler.com
api | staging.api.artcompiler.com | api.artcompiler.com
l0 | staging.l0.artcompiler.com | l0.artcompiler.com

**Comment by jeffdyer** [comment]
Like that that with the tweak of inserting 'gc' as a sub-domain

project | staging | prod
--- | --- | ---
app | staging.app.gc.artcompiler.com | app.gc.artcompiler.com
api | staging.api.gc.artcompiler.com | api.gc.artcompiler.com
l0 | staging.l0.gc.artcompiler.com | l0.gc.artcompiler.com

**Comment by KevinDyer** [comment]
SG, the next step is to add the `gc.artcompiler.com` domain in Cloud Run. @jeffdyer can you do this step. Docs are here https://cloud.google.com/run/docs/mapping-custom-domains#map

**Comment by jeffdyer** [comment]
One more tweak. Use 'gc' for the app instead of 'app.gc'.

project | staging | prod
--- | --- | ---
app | staging.gc.artcompiler.com | gc.artcompiler.com
api | staging.api.gc.artcompiler.com | api.gc.artcompiler.com
l0 | staging.l0.gc.artcompiler.com | l0.gc.artcompiler.com

**Comment by jeffdyer** [comment]
@KevinDyer Just FYI. I didn't see a staging.l0 service.

**Comment by KevinDyer** [comment]
doh, I forgot to add it. L0 issue
https://github.com/graffiticode/L0/issues/22

**Comment by jeffdyer** [comment]
All available services have been domain mapped.

**Comment by KevinDyer** [comment]
Great! Closing for now, I'll add a TODO in the above issue to add the mapping once the service is available

**Comment by jeffdyer** [comment]
Cool. I've added the DNS for staging.l0 too. It will be ready to go when you add the service and the google side domain mapping
